# vagrant plugin install vagrant-vbguest
# vagrant init centos/7;
# ulimit -n 4048; vagrant up


Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    
    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    
    config.vm.provision :shell do |shell|
        shell.inline = "sudo yum install -y git;
                        git clone https://github.com/mcjug2015/mfserver2.git /tmp/mfserver2/;
                        sudo sh /tmp/mfserver2/provisioning/misc/do_salt.sh;"
    end
    
    #config.vm.network "private_network", ip: "192.168.51.8"
end