# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''BEGIN;
            SELECT setval(pg_get_serial_sequence('"django_app_userconfirmation"','id'), 2000000);
            SELECT setval(pg_get_serial_sequence('"django_app_meetingtype"','id'), 2000000);
            SELECT setval(pg_get_serial_sequence('"django_app_meeting_types"','id'), 2000000);
            SELECT setval(pg_get_serial_sequence('"django_app_meeting"','id'), 2000000);
            SELECT setval(pg_get_serial_sequence('"django_app_meetingnotthere"','id'), 2000000);
            SELECT setval(pg_get_serial_sequence('"auth_user"','id'), 2000000);
            COMMIT;''',
            '''BEGIN;
            SELECT setval(pg_get_serial_sequence('"django_app_userconfirmation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_app_userconfirmation";
            SELECT setval(pg_get_serial_sequence('"django_app_meetingtype"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_app_meetingtype";
            SELECT setval(pg_get_serial_sequence('"django_app_meeting_types"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_app_meeting_types";
            SELECT setval(pg_get_serial_sequence('"django_app_meeting"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_app_meeting";
            SELECT setval(pg_get_serial_sequence('"django_app_meetingnotthere"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_app_meetingnotthere";
            SELECT setval(pg_get_serial_sequence('"auth_user"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_user";
            COMMIT;''')
    ]
