# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 00:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone


def forwards_func(apps, schema_editor):
    ''' add an admin user '''
    user = User(pk=1000000, username="mf_admin", is_active=True,
                is_superuser=True, is_staff=True,
                last_login=timezone.now(),
                email="mf_test@test.com",
                date_joined=timezone.now())
    user.set_password('mf_admin')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20160921_0033'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
