# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:25
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    ''' add an admin user '''
    user = User(username="mf_admin", is_active=True,
                is_superuser=True, is_staff=True,
                last_login=timezone.now(),
                email="mf_test@test.com",
                date_joined=timezone.now())
    user.set_password('mf_admin')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20170626_1801'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
