# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20160921_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMeeting',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('django_app.meeting',),
        ),
    ]
