# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_mapmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='django_app.MeetingType'),
        ),
    ]
