# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_userconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='conf_type',
            field=models.CharField(default='registration', max_length=64),
        ),
    ]
